name: ci-application-dev

on: workflow_dispatch

jobs:
  call-workflow-passing-data:
    uses: lifecompanionaac/lifecompanion-fv/.github/workflows/ci-lifecompanion.yml@master
    with:
      target_env: dev
      runs_on: ubuntu-latest
      gradle_command: :lc-app:publishApplication
      download_build_resources: true
    secrets:
      framework_server_url: ${{ secrets.LIFECOMPANION_FRAMEWORK_SERVER_URL_DEV }}
      framework_server_login: ${{ secrets.LIFECOMPANION_FRAMEWORK_SERVER_LOGIN_DEV }}
      framework_server_password: ${{ secrets.LIFECOMPANION_FRAMEWORK_SERVER_PASSWORD_DEV }}
      app_server_url: ${{ secrets.LIFECOMPANION_APP_SERVER_URL_DEV }}
      app_server_query_parameters: ${{ secrets.LIFECOMPANION_APP_SERVER_QUERY_PARAMETERS_DEV }}
      app_server_public_key: ${{ secrets.LIFECOMPANION_APP_SERVER_PUBLIC_KEY_DEV }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
