name: ci-plugin-prod

on: 
  workflow_dispatch:
    inputs:
      pluginJarName:
        description: 'Plugin file name (should be located in lc-plugins-jar directory)'     
        required: true

jobs:
  call-workflow-passing-data:
    uses: lifecompanionaac/lifecompanion/.github/workflows/ci-lifecompanion.yml@master
    with:
      target_env: prod
      runs_on: ubuntu-latest
      gradle_command: publishPluginJar -PpluginJarFile=lc-plugins-jar/${{ github.event.inputs.pluginJarName }}
    secrets:
      framework_server_url: ${{ secrets.LIFECOMPANION_FRAMEWORK_SERVER_URL_PROD }}
      framework_server_login: ${{ secrets.LIFECOMPANION_FRAMEWORK_SERVER_LOGIN_PROD }}
      framework_server_password: ${{ secrets.LIFECOMPANION_FRAMEWORK_SERVER_PASSWORD_PROD }}
      app_server_url: ${{ secrets.LIFECOMPANION_APP_SERVER_URL_PROD }}
      app_server_public_key: ${{ secrets.LIFECOMPANION_APP_SERVER_PUBLIC_KEY_PROD }}
